#ifndef ESTESQL_ASSETS_PATHS_H
#define ESTESQL_ASSETS_PATHS_H

#define CONTENT_FILE_EXTENSION ".data"
#define DEFINITION_FILE_EXTENSION ".def"
#define INDEX_FILE_EXTENSION ".idx"
#define KEY_FILE_EXTENSION ".key"



#endif //ESTESQL_ASSETS_PATHS_H
