#ifndef ESTESQL_STRING_DELIMITERS_H
#define ESTESQL_STRING_DELIMITERS_H

#define SPACE_DELIMITER ' '
#define COMA_DELIMITER ','
#define PARENTHESIS_OPEN_DELIMITER '('
#define PARENTHESIS_CLOSE_DELIMITER ')'

#endif //ESTESQL_STRING_DELIMITERS_H
